name: Algolia Crawler

on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types:
      - completed
  workflow_dispatch:  # For manual trigger


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.5
        id: algolia_crawler
        with: # mandatory parameters
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://gama-platform.org'
          crawler-name: 'gama-platform'
