# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Github Travis

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ sources ]
  workflow_dispatch:  # For manual trigger
  repository_dispatch: # For POST request trigger
    types: automated-generation

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare git
        run: |
          git config --global user.name "${{ secrets.BOT_GH_NAME}}"
          git config --global user.email "${{ secrets.BOT_GH_EMAIL}}"

      - name: Apply netrc creds with direct input again
        uses: little-core-labs/netrc-creds@master
        with:
          machine: github.com
          login: ${{ secrets.BOT_GH_NAME}}
          password: ${{ secrets.BOT_TOKEN}}
          
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64          
      - run: pip install typing

      #
      # PRE-COMPILE
      #
      - name: Get latest wiki
        run: git clone --depth 1 https://github.com/gama-platform/gama.wiki.git

      - name: Reorganise folders to be more Docusaurus-friendly
        shell: bash
        run: $GITHUB_WORKSPACE/script/unstructurize.sh

      - name: Enforce wiki MDX compliance
        shell: sh
        run: |
          $GITHUB_WORKSPACE/script/link_fixer.sh
          # Turn wiki MDX compliante
          find ./docs -name "*md" -exec python $GITHUB_WORKSPACE/script/escapingTags.py -i {} -o {} \;

      - name: Generate Sidebar 
        run: |
          python $GITHUB_WORKSPACE/script/generateSidebar.py > $GITHUB_WORKSPACE/website/sidebars.json
          cat $GITHUB_WORKSPACE/website/sidebars.json

      - name: Auto header
        shell: sh
        run: $GITHUB_WORKSPACE/script/autoHeader.sh

      - name: Finish cleaning docs folder
        shell: bash
        run: $GITHUB_WORKSPACE/script/finalClean.sh

      #
      # COMPILATION
      #

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install Docusaurus
        run: yarn install
        working-directory: ./website

      - name: Build & Publish Docusaurus
        run: yarn deploy
        working-directory: ./website
        env:
          GIT_USER: ${{ secrets.BOT_GH_NAME}}

      # We don't know when the site will be deployed, we just wait a few seconds
      # Better solutions can be found
      # https://github.com/algolia/algoliasearch-crawler-github-actions/blob/main/examples/github_pages.yml#L15-L18
      # -> Current average 7-8m
      - name: Sleep for 10m
        run: sleep 600
      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.15
        id: algolia_crawler
        with: # mandatory parameters
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://gama-platform.org'